/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gingerpipe.afp;

public class Main {

    public static void main(String[] args) {
        Shell shell = new Shell();
    }
}
